-- SQL script to create tables and sequences for Sistema Financiero

-- Creating Sequences
CREATE SEQUENCE usuarios_seq;
CREATE SEQUENCE clientes_seq;
CREATE SEQUENCE cuentas_seq;
CREATE SEQUENCE transacciones_seq;
CREATE SEQUENCE asesores_seq;

-- Creating USUARIOS Table
CREATE TABLE USUARIOS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    EMAIL VARCHAR2(100),
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

-- Creating CLIENTES Table
CREATE TABLE CLIENTES (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    TELEFONO VARCHAR2(15),
    EMAIL VARCHAR2(100),
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

-- Creating CUENTAS Table
CREATE TABLE CUENTAS (
    ID NUMBER PRIMARY KEY,
    TIPO_CUENTA VARCHAR2(50),
    SALDO NUMBER DEFAULT 0,
    ID_CLIENTE NUMBER REFERENCES CLIENTES(ID),
    FECHA_APERTURA DATE DEFAULT SYSDATE
);

-- Creating TRANSACCIONES Table
CREATE TABLE TRANSACCIONES (
    ID NUMBER PRIMARY KEY,
    TIPO_TRANSACCION VARCHAR2(50),
    MONTO NUMBER,
    ID_CUENTA NUMBER REFERENCES CUENTAS(ID),
    FECHA_TRANSACCION DATE DEFAULT SYSDATE
);

-- Creating ASESORES Table
CREATE TABLE ASESORES (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    EMAIL VARCHAR2(100),
    TELEFONO VARCHAR2(15),
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

-- Inserting test data into USUARIOS
INSERT INTO USUARIOS (ID, NOMBRE, EMAIL) VALUES (usuarios_seq.NEXTVAL, 'John Doe', 'johndoe@example.com');
INSERT INTO USUARIOS (ID, NOMBRE, EMAIL) VALUES (usuarios_seq.NEXTVAL, 'Jane Smith', 'janesmith@example.com');

-- Inserting test data into CLIENTES
INSERT INTO CLIENTES (ID, NOMBRE, APELLIDO, TELEFONO, EMAIL) VALUES (clientes_seq.NEXTVAL, 'Carlos', 'Pérez', '555-0123', 'carlos.perez@example.com');
INSERT INTO CLIENTES (ID, NOMBRE, APELLIDO, TELEFONO, EMAIL) VALUES (clientes_seq.NEXTVAL, 'María', 'González', '555-0456', 'maria.gonzalez@example.com');

-- Inserting test data into CUENTAS
INSERT INTO CUENTAS (ID, TIPO_CUENTA, SALDO, ID_CLIENTE) VALUES (cuentas_seq.NEXTVAL, 'Ahorros', 1000, 1);
INSERT INTO CUENTAS (ID, TIPO_CUENTA, SALDO, ID_CLIENTE) VALUES (cuentas_seq.NEXTVAL, 'Corriente', 2000, 2);

-- Inserting test data into TRANSACCIONES
INSERT INTO TRANSACCIONES (ID, TIPO_TRANSACCION, MONTO, ID_CUENTA) VALUES (transacciones_seq.NEXTVAL, 'Depósito', 500, 1);
INSERT INTO TRANSACCIONES (ID, TIPO_TRANSACCION, MONTO, ID_CUENTA) VALUES (transacciones_seq.NEXTVAL, 'Retiro', 200, 2);

-- Inserting test data into ASESORES
INSERT INTO ASESORES (ID, NOMBRE, EMAIL, TELEFONO) VALUES (asesores_seq.NEXTVAL, 'Ana López', 'ana.lopez@example.com', '555-0789');
INSERT INTO ASESORES (ID, NOMBRE, EMAIL, TELEFONO) VALUES (asesores_seq.NEXTVAL, 'Luis Fernández', 'luis.fernandez@example.com', '555-0987');
